version: '3.1'
services:
  build-angular-docker:
    image: adorsys/ci-build:latest
    volumes:
      - ./:/opt/src
    working_dir: /opt/src
    entrypoint: ""
    command:
      - /opt/src/docker/compile/build.cmd.bash
